# Generated by Django 3.1.4 on 2020-12-28 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20201228_0728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariationoption',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='product_variation_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.productvariationoption'),
        ),
    ]
