# Generated by Django 3.1.4 on 2021-01-14 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20210103_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_variation_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.productvariationoption'),
        ),
        migrations.DeleteModel(
            name='OrderDetails',
        ),
    ]
