# Generated by Django 3.1.4 on 2021-01-21 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_variation_option',
        ),
    ]
