# Generated by Django 3.1.4 on 2021-01-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20210122_0634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_variation_option',
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
