# Generated by Django 3.1.4 on 2021-01-22 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20210122_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
